version: '2.30'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always

  # Node api service
  api:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
    ports:
      # local->container
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_DB_URI: mongodb://mongo_db:27017/script
      OPENAI_API_KEY: sk_test
    depends_on: 
      - mongo_db