version: '2.30'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always

  # Node api service
  api:
    build:
      context: ../backend
    ports:
      # local->container
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_DB_URI: mongodb://mongo_db:27017/script
      OPENAI_API_KEY: sk_test
      OPENAI_BASE_URL: http://wiremock:8080/ai
    depends_on: 
      - mongo_db
  wiremock:
    image: "wiremock/wiremock:latest"
    ports:
      # local->container
      - 8080:8080
    volumes:
      - ./wiremock:/home/wiremock
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]