version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      MONGO_DB_URI: mongodb://mongo:27017/scripts
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:3001/api/scripts
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
