name: Acceptance Stage

on:
  push:
    branches:
      - 193-move-acceptance-test-stage-to-a-separate-file

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    env:
      MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      NODE_ENV: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # - name: Install testing dependencies
      #   working-directory: ./system-test
      #   run: npm install

      # - name: Install docker compose
      #   run: |
      #     curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #     chmod +x /usr/local/bin/docker-compose

      # - name: Login to AWS ECR
      #   uses: aws-actions/amazon-ecr-login@v1
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check image is Published
        env:
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr describe-images --repository-name $ECR_REPOSITORY --region $AWS_REGION | jq -r '.imageDetails[0].imagePushedAt'

      # - name: Run docker-compose
      #   working-directory: ./system-test
      #   env:
      #     ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
      #   run: |
      #     docker-compose up -d

      # - name: Run acceptance tests
      #   working-directory: ./system-test
      #   run: |
      #     npm run test:acceptance

      # - name: Stop docker-compose
      #   working-directory: ./system-test
      #   run: |
      #     docker-compose down
