name: Pre-commit stage

on:
  pull_request:
    branches:
      - master #fixme

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm run install:backend

      - name: Build Backend
        run: |
          npm run build:backend

      - name: Run Unit Tests
        run: |
          npm run test:backend:unit

      - name: Run Narrow Integration Tests
        run: |
          npm run test:backend:integration

      - name: Run Component Tests
        run: |
          npm run test:backend:component

      - name: Run Contract Provider Verification Tests
        run: |
          npm run test:backend:contract

      - name: Run linter
        run: |
          npm run lint:backend

  frontend:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm run install:frontend

      - name: Build Frontend
        run: |
          npm run build:frontend

      - name: Run Unit Tests
        run: |
          npm run test:frontend:unit

      - name: Run Narrow Integration Tests
        run: |
          npm run test:frontend:integration

      - name: Run Component Tests
        run: |
          npm run test:frontend:component

      - name: Run Contract Provider Verification Tests
        run: |
          npm run test:frontend:contract
