name: Commit stage pipeline

on:
  push:
    branches-ignore:
      - main
      
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm run install:backend

      - name: Build Backend
        run: |
          npm run build:backend

      - name: Run Unit Tests
        run: |
          npm run test:backend:unit

      - name: Run Narrow Integration Tests
        run: |
          npm run test:backend:integration

      - name: Run Component Tests
        run: |
          npm run test:backend:component

      - name: Run Contract Provider Verification Tests
        run: |
          npm run test:backend:contract

      - name: Check lint in backend
          working-directory: ./backend
          run: |
            npm run lint

  frontend:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm run install:frontend

      - name: Build Frontend
        run: |
          npm run build:frontend

      - name: Run Unit Tests
        run: |
          npm run test:frontend:unit

      - name: Run Narrow Integration Tests
        run: |
          npm run test:frontend:integration

      - name: Run Component Tests
        run: |
          npm run test:frontend:component

      - name: Run Contract Provider Verification Tests
        run: |
          npm run test:frontend:contract
