name: Production Stage

on:
  workflow_dispatch:

jobs:
  trigger-production-release:
    uses: ./.github/workflows/release.yml
    with:
      environment: prod

  system-tests:
    runs-on: ubuntu-latest
    needs: trigger-production-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if server is running
        run: |
          echo "Checking if the backend server is up..."
          curl -f ${{ vars.BACKEND_PROD_ENV_URL }}|| exit 1

      - name: Run Smoke Tests
        run: echo "Running smoke tests..."
