name: Production Stage

on:
  workflow_dispatch:

jobs:
  trigger-production-release:
    uses: ./.github/workflows/release.yml
    with:
      environment: prod
    secrets: inherit

  smoke-tests:
    needs: trigger-production-release
    uses: ./.github/workflows/smoke-tests.yml
    with:
      backend_url: http://${{ vars.EB_PROD_ENV }}.us-east-1.elasticbeanstalk.com
