name: Run Smoke Tests

on:
  workflow_call:
    inputs:
      backend_url:
        required: true
        type: string
      frontend_url:
          required: true
          type: string

jobs:
  smoke-tests:
    name: Run smoke tests
    runs-on: ubuntu-latest
    env:
      backend_url: ${{ inputs.BACKEND_UAT_ENV_URL }}
      frontend_url: ${{ inputs.FRONTEND_UAT_ENV_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory: ./system-test
        run: npm install

      - name: Run Smoke Tests
        working-directory: ./system-test
        run: npx jest smoke