name: Run Smoke Tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      backend_url: ${{ vars.BACKEND_UAT_ENV_URL }}
      frontend_url: ${{ vars.FRONTEND_UAT_ENV_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm run install:system-test

      - name: Run Smoke Tests
        run: |
          npm run test:smoke