name: UAT Stage

on:
  workflow_dispatch:

jobs:
  trigger-uat-release:
    uses: ./.github/workflows/release.yml
    with:
      environment: uat
    secrets: inherit

  smoke-tests:
    needs: trigger-uat-release
    uses: ./.github/workflows/smoke-tests.yml
    with:
      backend_url: http://${{ vars.EB_UAT_ENV }}.us-east-1.elasticbeanstalk.com
